#index:                   //name de la route
#    path: /              //route
#    controller: App\Controller\DefaultController::index // fonction

# page:
#   path: /page
#   controller: App\Controller\PageController::pageFonction